class Config:
    # Map generation
    MAP_MIN_WIDTH = 12
    MAP_ASPECT_RATIO = 1 / 2.0
    MAP_RING_COUNT_MIN = 2
    MAP_RING_COUNT_MAX = 20
    MIN_EMPTY_CELLS_PERCENT = 10
    MAX_EMPTY_CELLS_PERCENT = 20
    MIN_EGG_CELLS_PERCENT = 10
    MAX_EGG_CELLS_PERCENT = 28
    MIN_FOOD_CELLS_PERCENT = 10
    MAX_FOOD_CELLS_PERCENT = 30
    STARTING_HILL_DISTANCE = 2

    # Gameplay
    MAX_ANT_LOSS = 3
    FRAMES_PER_TURN = 1
    MAX_TURNS = 100 * FRAMES_PER_TURN

    # Rules
    FIGHTING_ANTS_KILL = False
    LOSING_ANTS_CANT_MOVE = False
    LOSING_ANTS_CANT_CARRY = True
    FORCE_SINGLE_HILL = False
    ENABLE_EGGS = True
    SCORES_IN_IO = True

    # Board
    VERTICAL_CUTOFF = 0.6
